"""estrutura inicial

Revision ID: 24bfe417f249
Revises: 
Create Date: 2025-04-06 00:08:51.458608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bfe417f249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('integrantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Enum('GRADUANDO', 'MESTRANDO', 'DOUTORANDO', 'POS_DOUTORANDO', 'PROFESSOR', name='categoriaenum'), nullable=False),
    sa.Column('valor_mensal', sa.Float(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontuacao_primeiro_colocado', sa.Integer(), nullable=False),
    sa.Column('reducao_pontos_por_posicao', sa.Integer(), nullable=False),
    sa.Column('pontuacao_minima', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_gasto', sa.DateTime(), nullable=True),
    sa.Column('comprovante_path', sa.String(length=255), nullable=True),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'AGUARDANDO_VALIDACAO', 'VALIDADO', 'REJEITADO', name='statuspagamentoenum'), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_validacao', sa.DateTime(), nullable=True),
    sa.Column('comprovante_path', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premiacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('data_premiacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premiacoes_semestrais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Enum('PRIMEIRO', 'SEGUNDO', name='semestreenum'), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('data_premiacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_semestral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Enum('PRIMEIRO', 'SEGUNDO', name='semestreenum'), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_semestral')
    op.drop_table('premiacoes_semestrais')
    op.drop_table('premiacoes')
    op.drop_table('pagamentos')
    op.drop_table('gastos')
    op.drop_table('configuracoes')
    op.drop_table('integrantes')
    op.drop_table('administradores')
    # ### end Alembic commands ###
