"""pontuação

Revision ID: 29e3bb9b7813
Revises: d43354f7f174
Create Date: 2025-03-29 15:08:44.793765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e3bb9b7813'
down_revision = 'd43354f7f174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontuacao_minima', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('pontuacao_minima')

    # ### end Alembic commands ###
