"""adicionar_campo_data_envio_pagamento

Revision ID: d11ea33e67a4
Revises: d6e2e2cf6d75
Create Date: 2025-03-28 22:52:23.032076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd11ea33e67a4'
down_revision = 'd6e2e2cf6d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
