"""Add pontuacao_minima to ConfiguracaoSistema

Revision ID: d43354f7f174
Revises: d11ea33e67a4
Create Date: 2025-03-29 14:53:05.363773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43354f7f174'
down_revision = 'd11ea33e67a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontuacao_minima', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('pontuacao_minima')

    # ### end Alembic commands ###
