"""adicionar_campo_data_envio_pagamento

Revision ID: d6e2e2cf6d75
Revises: 626332d8eace
Create Date: 2025-03-28 22:17:39.795580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e2e2cf6d75'
down_revision = '626332d8eace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###
